version: 2.1
docker:
  - image: circleci/node
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            - run: yarn e2e
workflows:
    build-and-test:
      jobs:
        - build-and-test
